# --- Server Config ---
server.port=8083

# --- Application Name ---
spring.application.name=async-service

# --- Async Thread Pool Config (BOTTLENECK) ---
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=10

# --- Logging ---
logging.level.com.example.asyncservice=DEBUG
