# --- Server Config ---
server.port=8081

# --- Application Name ---
spring.application.name=direct-service

# --- Logging Config ---
logging.level.com.example.directservice=DEBUG

# --- THIẾT LẬP BẪY TÀI NGUYÊN (DEMO) ---
# Giới hạn số luồng xử lý xuống 5 (Mặc định 200) - TẠO BOTTLENECK
server.tomcat.threads.max=5
# Giới hạn hàng chờ đợi kết nối xuống 10
server.tomcat.accept-count=10
# Giới hạn số connection đồng thời
server.tomcat.max-connections=10
